### ISSUE TITLE
Why do you count Title 12 as a single intent?

### ISSUE THREAD

**Issue by zsc19** [TRUMANCFY/SLIM#1]
The article mentions “Recently, models that learn these two tasks jointly achieve better performance by capturing semantic dependencies between slots and intents [6, 7, 8, 9, 10, 11, 12, 13].    The aforementioned methods assume only a single intent in an utterance.”.
**Why do you count Title 12 as a single intent?** 
“[12] Libo Qin, Fuxuan Wei, Tianbao Xie, Xiao Xu, Wanxiang Che, and Ting Liu, “GL-GIN: fast and accurate non-autoregressive model for joint multiple intent detection and slot filling,” in ACL/IJCNLP (1). 2021, pp.
178–188, Association for Computational Linguistics.”

**Comment by TRUMANCFY** [comment]
Thanks for your comment! We admit and apologize for this flaw. GL-GIN should be a multiple-intent method.
